import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SimpleQueryProvider } from "@/lib/providers/simple-query-provider";
import { ErrorBoundary } from "@/components/error-boundary";
import { Toaster } from "sonner";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        <ErrorBoundary>
          <SimpleQueryProvider>
            {children}
            <Toaster richColors position="top-right" />
          </SimpleQueryProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
